import { pgEnum } from "drizzle-orm/pg-core";

export const itemType = pgEnum("itemType", [
    "Artwork",
    "AudioRecording",
    "Bill",
    "BlogPost",
    "Book",
    "BookSection",
    "Case",
    "ComputerProgram",
    "ConferencePaper",
    "DictionaryEntry",
    "Document",
    "Email",
    "EncyclopediaArticle",
    "Film",
    "ForumPost",
    "Hearing",
    "InstantMessage",
    "Interview",
    "JournalArticle",
    "Letter",
    "MagazineArticle",
    "Manuscript",
    "Map",
    "NewspaperArticle",
    "Note",
    "Patent",
    "Podcast",
    "Presentation",
    "RadioBroadcast",
    "Report",
    "Statute",
    "TvBroadcast",
    "Thesis",
    "VideoRecording",
    "Webpage"
  ]);
  