export const columns = {
  Artwork: {
    id: true,
    version: true,
    itemType: true,
    key: true,
    title: true,
    abstractNote: true,
    artworkMedium: true,
    artworkSize: true,
    date: true,
    shortTitle: true,
    archive: true,
    archiveLocation: true,
    libraryCatalog: true,
    callNumber: true,
    url: true,
    accessDate: true,
    rights: true,
    extra: true,
  },
  Attachment: {
    id: true,
    version: true,
    itemType: true,
    key: true,
    title: true,
    accessDate: true,
    url: true,
    note: true,
    contentType: true,
    charset: true,
    filename: true,
    md5: true,
    mtime: true,
  },
  AudioRecording: {
    id: true,
    version: true,
    itemType: true,
    key: true,
    title: true,
    abstractNote: true,
    audioRecordingFormat: true,
    seriesTitle: true,
    volume: true,
    numberOfVolumes: true,
    place: true,
    label: true,
    date: true,
    runningTime: true,
    ISBN: true,
    shortTitle: true,
    archive: true,
    archiveLocation: true,
    libraryCatalog: true,
    callNumber: true,
    url: true,
    accessDate: true,
    rights: true,
    extra: true,
  },
  Bill: {
    id: true,
    version: true,
    itemType: true,
    key: true,
    title: true,
    abstractNote: true,
    billNumber: true,
    code: true,
    codeVolume: true,
    section: true,
    codePages: true,
    legislativeBody: true,
    session: true,
    history: true,
    date: true,
    shortTitle: true,
    url: true,
    accessDate: true,
    rights: true,
    extra: true,
  },
  BlogPost: {
    id: true,
    version: true,
    itemType: true,
    key: true,
    title: true,
    abstractNote: true,
    blogTitle: true,
    websiteType: true,
    date: true,
    shortTitle: true,
    url: true,
    accessDate: true,
    rights: true,
    extra: true,
  },
  Book: {
    id: true,
    version: true,
    itemType: true,
    key: true,
    title: true,
    abstractNote: true,
    series: true,
    seriesNumber: true,
    volume: true,
    numberOfVolumes: true,
    edition: true,
    place: true,
    publisher: true,
    date: true,
    numPages: true,
    ISBN: true,
    shortTitle: true,
    url: true,
    accessDate: true,
    archive: true,
    archiveLocation: true,
    libraryCatalog: true,
    callNumber: true,
    rights: true,
    extra: true,
  },
  BookSection: {
    id: true,
    version: true,
    itemType: true,
    key: true,
    title: true,
    abstractNote: true,
    bookTitle: true,
    series: true,
    seriesNumber: true,
    volume: true,
    numberOfVolumes: true,
    edition: true,
    place: true,
    publisher: true,
    date: true,
    pages: true,
    ISBN: true,
    shortTitle: true,
    url: true,
    accessDate: true,
    archive: true,
    archiveLocation: true,
    libraryCatalog: true,
    callNumber: true,
    rights: true,
    extra: true,
  },
  Case: {
    id: true,
    version: true,
    itemType: true,
    key: true,
    caseName: true,
    abstractNote: true,
    court: true,
    dateDecided: true,
    docketNumber: true,
    reporter: true,
    reporterVolume: true,
    firstPage: true,
    history: true,
    shortTitle: true,
    url: true,
    accessDate: true,
    rights: true,
    extra: true,
  },
  ComputerProgram: {
    id: true,
    version: true,
    itemType: true,
    key: true,
    title: true,
    abstractNote: true,
    seriesTitle: true,
    versionNumber: true,
    date: true,
    system: true,
    place: true,
    company: true,
    programmingLanguage: true,
    ISBN: true,
    shortTitle: true,
    url: true,
    rights: true,
    archive: true,
    archiveLocation: true,
    libraryCatalog: true,
    callNumber: true,
    accessDate: true,
    extra: true,
  },
  ConferencePaper: {
    id: true,
    version: true,
    itemType: true,
    key: true,
    title: true,
    abstractNote: true,
    date: true,
    proceedingsTitle: true,
    conferenceName: true,
    place: true,
    publisher: true,
    volume: true,
    pages: true,
    series: true,
    DOI: true,
    ISBN: true,
    shortTitle: true,
    url: true,
    accessDate: true,
    archive: true,
    archiveLocation: true,
    libraryCatalog: true,
    callNumber: true,
    rights: true,
    extra: true,
  },
  DictionaryEntry: {
    id: true,
    version: true,
    itemType: true,
    key: true,
    title: true,
    abstractNote: true,
    dictionaryTitle: true,
    series: true,
    seriesNumber: true,
    volume: true,
    numberOfVolumes: true,
    edition: true,
    place: true,
    publisher: true,
    date: true,
    pages: true,
    ISBN: true,
    shortTitle: true,
    url: true,
    accessDate: true,
    archive: true,
    archiveLocation: true,
    libraryCatalog: true,
    callNumber: true,
    rights: true,
    extra: true,
  },
  Document: {
    id: true,
    version: true,
    itemType: true,
    key: true,
    title: true,
    abstractNote: true,
    publisher: true,
    date: true,
    shortTitle: true,
    url: true,
    accessDate: true,
    archive: true,
    archiveLocation: true,
    libraryCatalog: true,
    callNumber: true,
    rights: true,
    extra: true,
  },
  Email: {
    id: true,
    version: true,
    itemType: true,
    key: true,
    subject: true,
    abstractNote: true,
    date: true,
    shortTitle: true,
    url: true,
    accessDate: true,
    rights: true,
    extra: true,
  },
  EncyclopediaArticle: {
    id: true,
    version: true,
    itemType: true,
    key: true,
    title: true,
    abstractNote: true,
    encyclopediaTitle: true,
    series: true,
    seriesNumber: true,
    volume: true,
    numberOfVolumes: true,
    edition: true,
    place: true,
    publisher: true,
    date: true,
    pages: true,
    ISBN: true,
    shortTitle: true,
    url: true,
    accessDate: true,
    archive: true,
    archiveLocation: true,
    libraryCatalog: true,
    callNumber: true,
    rights: true,
    extra: true,
  },
  Film: {
    id: true,
    version: true,
    itemType: true,
    key: true,
    title: true,
    abstractNote: true,
    distributor: true,
    date: true,
    genre: true,
    videoRecordingFormat: true,
    runningTime: true,
    shortTitle: true,
    url: true,
    accessDate: true,
    archive: true,
    archiveLocation: true,
    libraryCatalog: true,
    callNumber: true,
    rights: true,
    extra: true,
  },
  ForumPost: {
    id: true,
    version: true,
    itemType: true,
    key: true,
    title: true,
    abstractNote: true,
    forumTitle: true,
    postType: true,
    date: true,
    shortTitle: true,
    url: true,
    accessDate: true,
    rights: true,
    extra: true,
  },
  Hearing: {
    id: true,
    version: true,
    itemType: true,
    key: true,
    title: true,
    abstractNote: true,
    committee: true,
    place: true,
    publisher: true,
    numberOfVolumes: true,
    documentNumber: true,
    pages: true,
    legislativeBody: true,
    session: true,
    history: true,
    date: true,
    shortTitle: true,
    url: true,
    accessDate: true,
    rights: true,
    extra: true,
  },
  InstantMessage: {
    id: true,
    version: true,
    itemType: true,
    key: true,
    title: true,
    abstractNote: true,
    date: true,
    shortTitle: true,
    url: true,
    accessDate: true,
    rights: true,
    extra: true,
  },
  Interview: {
    id: true,
    version: true,
    itemType: true,
    key: true,
    title: true,
    abstractNote: true,
    date: true,
    interviewMedium: true,
    shortTitle: true,
    url: true,
    accessDate: true,
    archive: true,
    archiveLocation: true,
    libraryCatalog: true,
    callNumber: true,
    rights: true,
    extra: true,
  },
  JournalArticle: {
    id: true,
    version: true,
    itemType: true,
    key: true,
    title: true,
    abstractNote: true,
    publicationTitle: true,
    volume: true,
    issue: true,
    pages: true,
    date: true,
    series: true,
    seriesTitle: true,
    seriesText: true,
    journalAbbreviation: true,
    DOI: true,
    ISSN: true,
    shortTitle: true,
    url: true,
    accessDate: true,
    archive: true,
    archiveLocation: true,
    libraryCatalog: true,
    callNumber: true,
    rights: true,
    extra: true,
  },
  Letter: {
    id: true,
    version: true,
    itemType: true,
    key: true,
    title: true,
    abstractNote: true,
    letterType: true,
    date: true,
    shortTitle: true,
    url: true,
    accessDate: true,
    archive: true,
    archiveLocation: true,
    libraryCatalog: true,
    callNumber: true,
    rights: true,
    extra: true,
  },
  MagazineArticle: {
    id: true,
    version: true,
    itemType: true,
    key: true,
    title: true,
    abstractNote: true,
    publicationTitle: true,
    volume: true,
    issue: true,
    date: true,
    pages: true,
    ISSN: true,
    shortTitle: true,
    url: true,
    accessDate: true,
    archive: true,
    archiveLocation: true,
    libraryCatalog: true,
    callNumber: true,
    rights: true,
    extra: true,
  },
  Manuscript: {
    id: true,
    version: true,
    itemType: true,
    key: true,
    title: true,
    abstractNote: true,
    manuscriptType: true,
    place: true,
    date: true,
    numPages: true,
    shortTitle: true,
    url: true,
    accessDate: true,
    archive: true,
    archiveLocation: true,
    libraryCatalog: true,
    callNumber: true,
    rights: true,
    extra: true,
  },
  Map: {
    id: true,
    version: true,
    itemType: true,
    key: true,
    title: true,
    abstractNote: true,
    mapType: true,
    scale: true,
    seriesTitle: true,
    edition: true,
    place: true,
    publisher: true,
    date: true,
    ISBN: true,
    shortTitle: true,
    url: true,
    accessDate: true,
    archive: true,
    archiveLocation: true,
    libraryCatalog: true,
    callNumber: true,
    rights: true,
    extra: true,
  },
  NewspaperArticle: {
    id: true,
    version: true,
    itemType: true,
    key: true,
    title: true,
    abstractNote: true,
    publicationTitle: true,
    place: true,
    edition: true,
    date: true,
    section: true,
    pages: true,
    shortTitle: true,
    ISSN: true,
    url: true,
    accessDate: true,
    archive: true,
    archiveLocation: true,
    libraryCatalog: true,
    callNumber: true,
    rights: true,
    extra: true,
  },
  Note: {
    id: true,
    version: true,
    itemType: true,
    key: true,
    note: true,
  },
  Patent: {
    id: true,
    version: true,
    itemType: true,
    key: true,
    title: true,
    abstractNote: true,
    place: true,
    country: true,
    assignee: true,
    issuingAuthority: true,
    patentNumber: true,
    filingDate: true,
    pages: true,
    applicationNumber: true,
    priorityNumbers: true,
    issueDate: true,
    references: true,
    legalStatus: true,
    shortTitle: true,
    url: true,
    accessDate: true,
    rights: true,
    extra: true,
  },
  Podcast: {
    id: true,
    version: true,
    itemType: true,
    key: true,
    title: true,
    abstractNote: true,
    seriesTitle: true,
    episodeNumber: true,
    audioFileType: true,
    runningTime: true,
    url: true,
    accessDate: true,
    shortTitle: true,
    rights: true,
    extra: true,
  },
  Presentation: {
    id: true,
    version: true,
    itemType: true,
    key: true,
    title: true,
    abstractNote: true,
    presentationType: true,
    date: true,
    place: true,
    meetingName: true,
    url: true,
    accessDate: true,
    shortTitle: true,
    rights: true,
    extra: true,
  },
  RadioBroadcast: {
    id: true,
    version: true,
    itemType: true,
    key: true,
    title: true,
    abstractNote: true,
    programTitle: true,
    episodeNumber: true,
    audioRecordingFormat: true,
    place: true,
    network: true,
    date: true,
    runningTime: true,
    shortTitle: true,
    url: true,
    accessDate: true,
    archive: true,
    archiveLocation: true,
    libraryCatalog: true,
    callNumber: true,
    rights: true,
    extra: true,
  },
  Report: {
    id: true,
    version: true,
    itemType: true,
    key: true,
    title: true,
    abstractNote: true,
    reportNumber: true,
    reportType: true,
    seriesTitle: true,
    place: true,
    institution: true,
    date: true,
    pages: true,
    shortTitle: true,
    url: true,
    accessDate: true,
    archive: true,
    archiveLocation: true,
    libraryCatalog: true,
    callNumber: true,
    rights: true,
    extra: true,
  },
  Statute: {
    id: true,
    version: true,
    itemType: true,
    key: true,
    nameOfAct: true,
    abstractNote: true,
    code: true,
    codeNumber: true,
    publicLawNumber: true,
    dateEnacted: true,
    pages: true,
    section: true,
    session: true,
    history: true,
    shortTitle: true,
    url: true,
    accessDate: true,
    rights: true,
    extra: true,
  },
  Thesis: {
    id: true,
    version: true,
    itemType: true,
    key: true,
    title: true,
    abstractNote: true,
    thesisType: true,
    university: true,
    place: true,
    date: true,
    numPages: true,
    shortTitle: true,
    url: true,
    accessDate: true,
    archive: true,
    archiveLocation: true,
    libraryCatalog: true,
    callNumber: true,
    rights: true,
    extra: true,
  },
  TvBroadcast: {
    id: true,
    version: true,
    itemType: true,
    key: true,
    title: true,
    abstractNote: true,
    programTitle: true,
    episodeNumber: true,
    videoRecordingFormat: true,
    place: true,
    network: true,
    date: true,
    runningTime: true,
    shortTitle: true,
    url: true,
    accessDate: true,
    archive: true,
    archiveLocation: true,
    libraryCatalog: true,
    callNumber: true,
    rights: true,
    extra: true,
  },
  VideoRecording: {
    id: true,
    version: true,
    itemType: true,
    key: true,
    title: true,
    abstractNote: true,
    videoRecordingFormat: true,
    seriesTitle: true,
    volume: true,
    numberOfVolumes: true,
    place: true,
    studio: true,
    date: true,
    runningTime: true,
    ISBN: true,
    shortTitle: true,
    url: true,
    accessDate: true,
    archive: true,
    archiveLocation: true,
    libraryCatalog: true,
    callNumber: true,
    rights: true,
    extra: true,
  },
  Webpage: {
    id: true,
    version: true,
    itemType: true,
    key: true,
    title: true,
    abstractNote: true,
    websiteTitle: true,
    websiteType: true,
    date: true,
    shortTitle: true,
    url: true,
    accessDate: true,
    rights: true,
    extra: true,
  },
} as const;

export const displayColumns = {
  "Annotation": [],
  "Artwork": [
    "creators",
    "title",
    "abstractNote",
    "artworkMedium",
    "artworkSize",
    "date",
    "language",
    "shortTitle",
    "archive",
    "archiveLocation",
    "libraryCatalog",
    "callNumber",
    "url",
    "accessDate",
    "rights",
    "extra"
  ],
  "Attachment": [
    "creators",
    "title",
    "accessDate",
    "url"
  ],
  "AudioRecording": [
    "creators",
    "title",
    "abstractNote",
    "audioRecordingFormat",
    "seriesTitle",
    "volume",
    "numberOfVolumes",
    "place",
    "label",
    "date",
    "runningTime",
    "language",
    "ISBN",
    "shortTitle",
    "archive",
    "archiveLocation",
    "libraryCatalog",
    "callNumber",
    "url",
    "accessDate",
    "rights",
    "extra"
  ],
  "Bill": [
    "creators",
    "title",
    "abstractNote",
    "billNumber",
    "code",
    "codeVolume",
    "section",
    "codePages",
    "legislativeBody",
    "session",
    "history",
    "date",
    "language",
    "url",
    "accessDate",
    "shortTitle",
    "rights",
    "extra"
  ],
  "BlogPost": [
    "creators",
    "title",
    "abstractNote",
    "blogTitle",
    "websiteType",
    "date",
    "url",
    "accessDate",
    "language",
    "shortTitle",
    "rights",
    "extra"
  ],
  "Book": [
    "creators",
    "title",
    "abstractNote",
    "series",
    "seriesNumber",
    "volume",
    "numberOfVolumes",
    "edition",
    "place",
    "publisher",
    "date",
    "numPages",
    "language",
    "ISBN",
    "shortTitle",
    "url",
    "accessDate",
    "archive",
    "archiveLocation",
    "libraryCatalog",
    "callNumber",
    "rights",
    "extra"
  ],
  "BookSection": [
    "creators",
    "title",
    "abstractNote",
    "bookTitle",
    "series",
    "seriesNumber",
    "volume",
    "numberOfVolumes",
    "edition",
    "place",
    "publisher",
    "date",
    "pages",
    "language",
    "ISBN",
    "shortTitle",
    "url",
    "accessDate",
    "archive",
    "archiveLocation",
    "libraryCatalog",
    "callNumber",
    "rights",
    "extra"
  ],
  "Case": [
    "creators",
    "caseName",
    "abstractNote",
    "court",
    "dateDecided",
    "docketNumber",
    "reporter",
    "reporterVolume",
    "firstPage",
    "history",
    "language",
    "shortTitle",
    "url",
    "accessDate",
    "rights",
    "extra"
  ],
  "ComputerProgram": [
    "creators",
    "title",
    "abstractNote",
    "seriesTitle",
    "versionNumber",
    "date",
    "system",
    "place",
    "company",
    "programmingLanguage",
    "ISBN",
    "shortTitle",
    "url",
    "rights",
    "archive",
    "archiveLocation",
    "libraryCatalog",
    "callNumber",
    "accessDate",
    "extra"
  ],
  "ConferencePaper": [
    "creators",
    "title",
    "abstractNote",
    "date",
    "proceedingsTitle",
    "conferenceName",
    "place",
    "publisher",
    "volume",
    "pages",
    "series",
    "language",
    "DOI",
    "ISBN",
    "shortTitle",
    "url",
    "accessDate",
    "archive",
    "archiveLocation",
    "libraryCatalog",
    "callNumber",
    "rights",
    "extra"
  ],
  "Dataset": [
    "creators",
    "title",
    "abstractNote",
    "identifier",
    "type",
    "versionNumber",
    "date",
    "repository",
    "repositoryLocation",
    "format",
    "DOI",
    "citationKey",
    "url",
    "accessDate",
    "archive",
    "archiveLocation",
    "shortTitle",
    "language",
    "libraryCatalog",
    "callNumber",
    "rights",
    "extra"
  ],
  "DictionaryEntry": [
    "creators",
    "title",
    "abstractNote",
    "dictionaryTitle",
    "series",
    "seriesNumber",
    "volume",
    "numberOfVolumes",
    "edition",
    "place",
    "publisher",
    "date",
    "pages",
    "language",
    "ISBN",
    "shortTitle",
    "url",
    "accessDate",
    "archive",
    "archiveLocation",
    "libraryCatalog",
    "callNumber",
    "rights",
    "extra"
  ],
  "Document": [
    "creators",
    "title",
    "abstractNote",
    "publisher",
    "date",
    "language",
    "shortTitle",
    "url",
    "accessDate",
    "archive",
    "archiveLocation",
    "libraryCatalog",
    "callNumber",
    "rights",
    "extra"
  ],
  "Email": [
    "creators",
    "subject",
    "abstractNote",
    "date",
    "shortTitle",
    "url",
    "accessDate",
    "language",
    "rights",
    "extra"
  ],
  "EncyclopediaArticle": [
    "creators",
    "title",
    "abstractNote",
    "encyclopediaTitle",
    "series",
    "seriesNumber",
    "volume",
    "numberOfVolumes",
    "edition",
    "place",
    "publisher",
    "date",
    "pages",
    "ISBN",
    "shortTitle",
    "url",
    "accessDate",
    "language",
    "archive",
    "archiveLocation",
    "libraryCatalog",
    "callNumber",
    "rights",
    "extra"
  ],
  "Film": [
    "creators",
    "title",
    "abstractNote",
    "distributor",
    "date",
    "genre",
    "videoRecordingFormat",
    "runningTime",
    "language",
    "shortTitle",
    "url",
    "accessDate",
    "archive",
    "archiveLocation",
    "libraryCatalog",
    "callNumber",
    "rights",
    "extra"
  ],
  "ForumPost": [
    "creators",
    "title",
    "abstractNote",
    "forumTitle",
    "postType",
    "date",
    "language",
    "shortTitle",
    "url",
    "accessDate",
    "rights",
    "extra"
  ],
  "Hearing": [
    "creators",
    "title",
    "abstractNote",
    "committee",
    "place",
    "publisher",
    "numberOfVolumes",
    "documentNumber",
    "pages",
    "legislativeBody",
    "session",
    "history",
    "date",
    "language",
    "shortTitle",
    "url",
    "accessDate",
    "rights",
    "extra"
  ],
  "InstantMessage": [
    "creators",
    "title",
    "abstractNote",
    "date",
    "language",
    "shortTitle",
    "url",
    "accessDate",
    "rights",
    "extra"
  ],
  "Interview": [
    "creators",
    "title",
    "abstractNote",
    "date",
    "interviewMedium",
    "language",
    "shortTitle",
    "url",
    "accessDate",
    "archive",
    "archiveLocation",
    "libraryCatalog",
    "callNumber",
    "rights",
    "extra"
  ],
  "JournalArticle": [
    "creators",
    "title",
    "abstractNote",
    "publicationTitle",
    "volume",
    "issue",
    "pages",
    "date",
    "series",
    "seriesTitle",
    "seriesText",
    "journalAbbreviation",
    "language",
    "DOI",
    "ISSN",
    "shortTitle",
    "url",
    "accessDate",
    "archive",
    "archiveLocation",
    "libraryCatalog",
    "callNumber",
    "rights",
    "extra"
  ],
  "Letter": [
    "creators",
    "title",
    "abstractNote",
    "letterType",
    "date",
    "language",
    "shortTitle",
    "url",
    "accessDate",
    "archive",
    "archiveLocation",
    "libraryCatalog",
    "callNumber",
    "rights",
    "extra"
  ],
  "MagazineArticle": [
    "creators",
    "title",
    "abstractNote",
    "publicationTitle",
    "volume",
    "issue",
    "date",
    "pages",
    "language",
    "ISSN",
    "shortTitle",
    "url",
    "accessDate",
    "archive",
    "archiveLocation",
    "libraryCatalog",
    "callNumber",
    "rights",
    "extra"
  ],
  "Manuscript": [
    "creators",
    "title",
    "abstractNote",
    "manuscriptType",
    "place",
    "date",
    "numPages",
    "language",
    "shortTitle",
    "url",
    "accessDate",
    "archive",
    "archiveLocation",
    "libraryCatalog",
    "callNumber",
    "rights",
    "extra"
  ],
  "Map": [
    "creators",
    "title",
    "abstractNote",
    "mapType",
    "scale",
    "seriesTitle",
    "edition",
    "place",
    "publisher",
    "date",
    "language",
    "ISBN",
    "shortTitle",
    "url",
    "accessDate",
    "archive",
    "archiveLocation",
    "libraryCatalog",
    "callNumber",
    "rights",
    "extra"
  ],
  "NewspaperArticle": [
    "creators",
    "title",
    "abstractNote",
    "publicationTitle",
    "place",
    "edition",
    "date",
    "section",
    "pages",
    "language",
    "shortTitle",
    "ISSN",
    "url",
    "accessDate",
    "archive",
    "archiveLocation",
    "libraryCatalog",
    "callNumber",
    "rights",
    "extra"
  ],
  "Note": [],
  "Patent": [
    "creators",
    "title",
    "abstractNote",
    "place",
    "country",
    "assignee",
    "issuingAuthority",
    "patentNumber",
    "filingDate",
    "pages",
    "applicationNumber",
    "priorityNumbers",
    "issueDate",
    "references",
    "legalStatus",
    "language",
    "shortTitle",
    "url",
    "accessDate",
    "rights",
    "extra"
  ],
  "Podcast": [
    "creators",
    "title",
    "abstractNote",
    "seriesTitle",
    "episodeNumber",
    "audioFileType",
    "runningTime",
    "url",
    "accessDate",
    "language",
    "shortTitle",
    "rights",
    "extra"
  ],
  "Preprint": [
    "creators",
    "title",
    "abstractNote",
    "genre",
    "repository",
    "archiveID",
    "place",
    "date",
    "series",
    "seriesNumber",
    "DOI",
    "citationKey",
    "url",
    "accessDate",
    "archive",
    "archiveLocation",
    "shortTitle",
    "language",
    "libraryCatalog",
    "callNumber",
    "rights",
    "extra"
  ],
  "Presentation": [
    "creators",
    "title",
    "abstractNote",
    "presentationType",
    "date",
    "place",
    "meetingName",
    "url",
    "accessDate",
    "language",
    "shortTitle",
    "rights",
    "extra"
  ],
  "RadioBroadcast": [
    "creators",
    "title",
    "abstractNote",
    "programTitle",
    "episodeNumber",
    "audioRecordingFormat",
    "place",
    "network",
    "date",
    "runningTime",
    "language",
    "shortTitle",
    "url",
    "accessDate",
    "archive",
    "archiveLocation",
    "libraryCatalog",
    "callNumber",
    "rights",
    "extra"
  ],
  "Report": [
    "creators",
    "title",
    "abstractNote",
    "reportNumber",
    "reportType",
    "seriesTitle",
    "place",
    "institution",
    "date",
    "pages",
    "language",
    "shortTitle",
    "url",
    "accessDate",
    "archive",
    "archiveLocation",
    "libraryCatalog",
    "callNumber",
    "rights",
    "extra"
  ],
  "Standard": [
    "creators",
    "title",
    "abstractNote",
    "organization",
    "committee",
    "type",
    "number",
    "versionNumber",
    "status",
    "date",
    "publisher",
    "place",
    "DOI",
    "citationKey",
    "url",
    "accessDate",
    "archive",
    "archiveLocation",
    "shortTitle",
    "numPages",
    "language",
    "libraryCatalog",
    "callNumber",
    "rights",
    "extra"
  ],
  "Statute": [
    "creators",
    "nameOfAct",
    "abstractNote",
    "code",
    "codeNumber",
    "publicLawNumber",
    "dateEnacted",
    "pages",
    "section",
    "session",
    "history",
    "language",
    "shortTitle",
    "url",
    "accessDate",
    "rights",
    "extra"
  ],
  "Thesis": [
    "creators",
    "title",
    "abstractNote",
    "thesisType",
    "university",
    "place",
    "date",
    "numPages",
    "language",
    "shortTitle",
    "url",
    "accessDate",
    "archive",
    "archiveLocation",
    "libraryCatalog",
    "callNumber",
    "rights",
    "extra"
  ],
  "TvBroadcast": [
    "creators",
    "title",
    "abstractNote",
    "programTitle",
    "episodeNumber",
    "videoRecordingFormat",
    "place",
    "network",
    "date",
    "runningTime",
    "language",
    "shortTitle",
    "url",
    "accessDate",
    "archive",
    "archiveLocation",
    "libraryCatalog",
    "callNumber",
    "rights",
    "extra"
  ],
  "VideoRecording": [
    "creators",
    "title",
    "abstractNote",
    "videoRecordingFormat",
    "seriesTitle",
    "volume",
    "numberOfVolumes",
    "place",
    "studio",
    "date",
    "runningTime",
    "language",
    "ISBN",
    "shortTitle",
    "url",
    "accessDate",
    "archive",
    "archiveLocation",
    "libraryCatalog",
    "callNumber",
    "rights",
    "extra"
  ],
  "Webpage": [
    "creators",
    "title",
    "abstractNote",
    "websiteTitle",
    "websiteType",
    "date",
    "shortTitle",
    "url",
    "accessDate",
    "language",
    "rights",
    "extra"
  ]
}

export const columnLabels = {
  id: 'ID',
  version: 'Version',
  itemType: 'Resource Type',
  creators: 'Authors/Contributors',
  key: 'Key',
  title: 'Title',
  collectionsData: 'Collections',
  abstractNote: 'Abstract',
  language: "Language",
  languageName: "Language",
  artworkMedium: 'Medium',
  artworkSize: 'Size',
  date: 'Date',
  shortTitle: 'Short Title',
  archive: 'Archive',
  archiveLocation: 'Archive Location',
  libraryCatalog: 'Library Catalog',
  callNumber: 'Call Number',
  url: 'URL',
  accessDate: 'Access Date',
  rights: 'Rights',
  extra: 'Extra',
  note: 'Note',
  contentType: 'Content Type',
  charset: 'Character Set',
  filename: 'Filename',
  md5: 'MD5',
  mtime: 'Modified Time',
  audioRecordingFormat: 'Recording Format',
  seriesTitle: 'Series Title',
  volume: 'Volume',
  numberOfVolumes: 'Number of Volumes',
  place: 'Place',
  label: 'Label',
  ISBN: 'ISBN',
  billNumber: 'Bill Number',
  code: 'Code',
  codeVolume: 'Code Volume',
  section: 'Section',
  codePages: 'Code Pages',
  legislativeBody: 'Legislative Body',
  session: 'Session',
  history: 'History',
  blogTitle: 'Blog Title',
  websiteType: 'Website Type',
  series: 'Series',
  seriesNumber: 'Series Number',
  edition: 'Edition',
  publisher: 'Publisher',
  numPages: 'Number of Pages',
  bookTitle: 'Book Title',
  pages: 'Pages',
  caseName: 'Case Name',
  court: 'Court',
  dateDecided: 'Date Decided',
  docketNumber: 'Docket Number',
  reporter: 'Reporter',
  reporterVolume: 'Reporter Volume',
  firstPage: 'First Page',
  versionNumber: 'Version Number',
  system: 'System',
  company: 'Company',
  programmingLanguage: 'Programming Language',
  proceedingsTitle: 'Proceedings Title',
  conferenceName: 'Conference Name',
  DOI: 'DOI',
  dictionaryTitle: 'Dictionary Title',
  subject: 'Subject',
  encyclopediaTitle: 'Encyclopedia Title',
  distributor: 'Distributor',
  genre: 'Genre',
  videoRecordingFormat: 'Video Format',
  forumTitle: 'Forum Title',
  postType: 'Post Type',
  committee: 'Committee',
  documentNumber: 'Document Number',
  interviewMedium: 'Interview Medium',
  publicationTitle: 'Publication Title',
  issue: 'Issue',
  seriesText: 'Series Text',
  journalAbbreviation: 'Journal Abbreviation',
  ISSN: 'ISSN',
  letterType: 'Letter Type',
  manuscriptType: 'Manuscript Type',
  mapType: 'Map Type',
  scale: 'Scale',
  nameOfAct: 'Name of Act',
  codeNumber: 'Code Number',
  publicLawNumber: 'Public Law Number',
  dateEnacted: 'Date Enacted',
  country: 'Country',
  assignee: 'Assignee',
  issuingAuthority: 'Issuing Authority',
  patentNumber: 'Patent Number',
  filingDate: 'Filing Date',
  applicationNumber: 'Application Number',
  priorityNumbers: 'Priority Numbers',
  issueDate: 'Issue Date',
  references: 'References',
  legalStatus: 'Legal Status',
  episodeNumber: 'Episode Number',
  audioFileType: 'Audio File Type',
  runningTime: 'Running Time',
  presentationType: 'Presentation Type',
  meetingName: 'Meeting Name',
  programTitle: 'Program Title',
  network: 'Network',
  reportNumber: 'Report Number',
  reportType: 'Report Type',
  institution: 'Institution',
  thesisType: 'Thesis Type',
  university: 'University',
  studio: 'Studio',
  websiteTitle: 'Website Title',
  attachmentsData: 'Attachments',
} as const;
